[package]
name = "common"
version = "0.0.1"
authors = [""]

[lib]
name = "common"
path = "lib.rs"

[dependencies]
rustc-serialize = "0.3.16"

[dependencies.schedule_recv]
git = "https://github.com/PeterReid/schedule_recv"
