[package]
name = "tick"
version = "0.0.1"
authors = [""]

[lib]
name = "tick"
path = "lib.rs"

[dependencies.schedule_recv]
git = "https://github.com/PeterReid/schedule_recv"

[dependencies.common]
path = "../common"

[dependencies.tick_traits]
path = "../tick_traits"
